version: '3.8'


services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - sonarqube_network
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=admin
      - SONARQUBE_JDBC_PASSWORD=admin
    networks:
      - sonarqube_network
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - sonarqube_network

volumes:
  jenkins-data:
  postgresql-data:

networks:
  sonarqube_network:







